site:
  title: Documentaci√≥n Umapyoi Derby
  url: https://ninjascl.github.io/antora-docs-bootstrap
  start_page: "ROOT::index.adoc"

content:
  sources:
    - url: .
      branches: HEAD
      start_path: .

antora:
  extensions:
    - require: "@antora/lunr-extension"

asciidoc:
  extensions:
    - asciidoctor-emoji
    - asciidoctor-kroki
    #- "@djencks/asciidoctor-mathjax"
  attributes:
    kroki-fetch-diagram: true
    experimental: ""
    idprefix: ""
    idseparator: "-"
    page-pagination: ""
    highlightjs-theme: monokai
    highlightjs-languages: js, elixir, sql, yaml, html, css

ui:
  bundle:
    # https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    url: ui-bundle.zip
    snapshot: true
  # https://gitlab.com/antora/antora-ui-default/-/tree/master/src/partials
  supplemental_files: supplemental-ui/

output:
  dir: docs/
